FROM golang:1.16.15-bullseye

RUN apt-get update
RUN apt-get install curl unzip --yes

RUN curl -fsSL https://github.com/Masterminds/glide/releases/download/v0.13.3/glide-v0.13.3-linux-amd64.zip -o temp.zip
RUN unzip temp.zip
RUN mv linux-amd64/glide /bin

RUN mkdir -p $GOPATH/src/github.com/andrepinto/helmsman

VOLUME $GOPATH/src/github.com/andrepinto/helmsman/bin

COPY . $GOPATH/src/github.com/andrepinto/helmsman

WORKDIR $GOPATH/src/github.com/andrepinto/helmsman

RUN glide install
